import type { Metadata } from 'next';
import '../globals.css';
import TabBar from '@/components/layout/TabBar';
import QueryProvider from '@/components/providers/QueryProvider';
import { ReactNode } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <QueryProvider>
      <main>{children}</main>
      {/* 主要页面内容会在这里渲染 */}
      <TabBar />
    </QueryProvider>
  );
}
